# NumPy

In [1]:
import numpy as np

## Creation of a numpy array from a list

In [2]:
array_from_a_list = np.array([1, 2, 3, 4, 5])
print(array_from_a_list)

[1 2 3 4 5]


In [3]:
type(array_from_a_list)

numpy.ndarray

In [4]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

[1 2 3 4 5]


## 2D array

In [5]:
array_2d = np.array(
    [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
    ]
)

In [6]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
type(array_2d)

numpy.ndarray

## 3D array

In [8]:
array_3d = np.array([[[1, 2],[True, 4]],[[5.0, 6],[7, 8]],[[9, 10], [11, 12]]])

print(array_3d)

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [9]:
type(array_3d)

numpy.ndarray

In [10]:
array_2d.ndim

2

In [11]:
array_3d.ndim

3

In [12]:
array_from_a_list.shape

(5,)

In [13]:
array_2d.shape

(3, 3)

In [14]:
array_3d.shape

(3, 2, 2)

In [15]:
trial = np.array([1, 3, 'hey', 4], dtype = 'U')

In [16]:
print(trial)

['1' '3' 'hey' '4']


If you create an np.array with mixed data types, like np.array([1, 2, "Hello", 4]), NumPy does not throw an error. Instead, it implicitly typecasts all elements to a single, most accommodating data type.

How typecasting works
When you pass a list of mixed-type Python objects to np.array(), NumPy follows a set of promotion rules to find the most suitable common data type for all elements.
Find the most complex type: NumPy scans the input list to identify the most complex or flexible data type. The hierarchy for standard Python objects is: integers are simpler than floats, which are simpler than strings.
Promote all elements: Once the most accommodating type is found, NumPy converts every other element into that type.
Resulting dtype: The new array's dtype attribute will reflect the common data type.

For np.array([1, 2, "Hello", 4]):
The elements are two integers (1, 2), one string ("Hello"), and another integer (4).
The string "Hello" is the most complex type.
NumPy converts the integers 1, 2, and 4 into string representations '1', '2', and '4'.
The resulting array is array(['1', '2', 'Hello', '4']) with a dtype of <U5 (Unicode string with a maximum length of 5).

Why no error is shown
An error is not shown because NumPy's type promotion is designed to automatically handle mixed types by casting up to the most general type possible. It does this to maintain its core principle of working with homogeneous data and to avoid a crash when a simple conversion is possible.
Explicit vs. implicit conversion: NumPy will only throw an error if you explicitly tell it to convert to an incompatible data type. For example, if you were to force your array to an integer dtype, it would fail because the string "Hello" cannot be converted to an integer.
A "best guess" approach: By automatically casting, NumPy makes a "best guess" at what the user intended to do when faced with mixed data. This behavior is convenient but can hide potential performance issues if not used with care.

In [17]:
array_3d.dtype

dtype('float64')

In [18]:
array_ = np.array([5, -7.4, 'Hey', 7.4, True])

In [19]:
array_.dtype

dtype('<U32')

itemsize returns the size in bytes of each element present in array

In [20]:
print(f"item size of array_ is: {array_.itemsize}")

item size of array_ is: 128


data provides a direct buffer to the memory location where the actual array is present or stored

In [21]:
print(f"Data buffere is actually present at memory location: {array_.data}")

Data buffere is actually present at memory location: <memory at 0x7e71d99c53c0>


## Indexing and slicing in NumPy

In [22]:
array_from_a_list

array([1, 2, 3, 4, 5])

In [23]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
array_3d

array([[[ 1.,  2.],
        [ 1.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]])

In [25]:
print(array_from_a_list[2])

3


In [26]:
print(array_2d[1])

[4 5 6]


In [27]:
print(array_3d[0])

[[1. 2.]
 [1. 4.]]


In [28]:
print(array_2d[2][2])

9


In [29]:
print(array_2d[2, 2])

9


In [30]:
print(array_3d[1, 1, 1])

8.0


In [31]:
print(array_3d[1][1][1])

8.0


In [32]:
print(array_3d[1, 1][1])

8.0


In [33]:
print(array_from_a_list[1: 4])

[2 3 4]


In [34]:
print(array_2d[1:3])

[[4 5 6]
 [7 8 9]]


In [35]:
print(array_2d[1:3, 1:2])

[[5]
 [8]]


In [36]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(array_2d[0:3, 0:1])

[[1]
 [4]
 [7]]


In [38]:
print(array_2d[0:3][0:1])

[[1 2 3]]


In [39]:
print(array_2d[0:3, 0:2][0:1])

[[1 2]]


In [40]:
print(array_2d[0:3][0:2][0:1])

[[1 2 3]]


upar wale ka work flow aise hoga

In [41]:
print(array_2d[0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print(array_2d[0:3][0:2])

[[1 2 3]
 [4 5 6]]


In [43]:
print(array_2d[0:3][0:2][0:1])

[[1 2 3]]


In [44]:
print(array_2d[0:3][0:2][0:1, 0:2])

[[1 2]]


In [45]:
array_3d

array([[[ 1.,  2.],
        [ 1.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]])

In [46]:
print(array_3d[0:])

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [47]:
print(array_3d[0:3][0:2])

[[[1. 2.]
  [1. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [48]:
print(array_3d[0:3][0:2][0:1])

[[[1. 2.]
  [1. 4.]]]


In [49]:
print(array_3d[0:3][0:2][0:1][0:1])

[[[1. 2.]
  [1. 4.]]]


In [50]:
print(array_3d[0:3])

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [51]:
print(array_3d[0:3, 0:2])

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [52]:
print(array_3d[0:3,0:2,0:1])

[[[ 1.]
  [ 1.]]

 [[ 5.]
  [ 7.]]

 [[ 9.]
  [11.]]]


In [53]:
print(array_3d)

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [54]:
print(array_3d[0:2, 1, 1:])

[[4.]
 [8.]]


## Arithmetic Operations

In [55]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

# Addition
print(f"Addition of 2 two dimentional metrices: {a + b}")

# Subtraction
print(f"Subtraction of 2 two dimentional metrices: {a - b}")

# Multiplication
print(f"Multiplication of 2 two dimentional metrices: {a * b}")

# Division
print(f"Division of 2 two dimentional metrices: {a / b}")

# Power
print(f"Power of 2 two dimentional metrice: {a ** 2}")

Addition of 2 two dimentional metrices: [[11 22]
 [33 44]]
Subtraction of 2 two dimentional metrices: [[ -9 -18]
 [-27 -36]]
Multiplication of 2 two dimentional metrices: [[ 10  40]
 [ 90 160]]
Division of 2 two dimentional metrices: [[0.1 0.1]
 [0.1 0.1]]
Power of 2 two dimentional metrice: [[ 1  4]
 [ 9 16]]


## Methods in NumPy

### Transpose

In [56]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [57]:
print(arr.T)
# T is an attribute to use transpose

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Sorting

In [58]:
arr_1d = np.array([2, 1, 3, 5, 4, 10, 7, 6])

sorted_arr_1d = np.sort(arr_1d)
print(f"sorted array: {sorted_arr_1d}")

sorted array: [ 1  2  3  4  5  6  7 10]


In [59]:
arr_1d = np.sort(arr_1d)[::-1]
print(arr_1d)

[10  7  6  5  4  3  2  1]


In [60]:
arr = np.array([
    [3, 2, 1],
    [6, 5, 4]
])
sorted_arr = np.sort(arr)
print(f"Sorted 2D array: {sorted_arr}")

Sorted 2D array: [[1 2 3]
 [4 5 6]]


In [61]:
arr = np.array([
    [3, 2, 1],
    [6, 5, 4]
])
sorted_arr = np.sort(arr, axis=0)
print(f"Sorted 2D array: {sorted_arr}")

Sorted 2D array: [[3 2 1]
 [6 5 4]]


In [62]:
arr = np.array([
    [3, 2, 1],
    [6, 5, 4]
])
sorted_arr = np.sort(arr, axis = 1)
print(f"Sorted 2D array: {sorted_arr}")

Sorted 2D array: [[1 2 3]
 [4 5 6]]


In [63]:
arr = np.array([
    [6, 5, 4],
    [3, 2, 1]
])
sorted_arr = np.sort(arr, axis = 0)
print(f"Sorted 2D array: {sorted_arr}")

Sorted 2D array: [[3 2 1]
 [6 5 4]]


In [64]:
arr = np.array([
    [6, 5, 4],
    [3, 2, 1]
])
sorted_arr = np.sort(arr, axis = 0)
print(f"Sorted 2D array: {sorted_arr}")

Sorted 2D array: [[3 2 1]
 [6 5 4]]


In [65]:
arr = arr.T
print(arr)

[[6 3]
 [5 2]
 [4 1]]


In [66]:
arr = np.sort(arr)
print(arr)

[[3 6]
 [2 5]
 [1 4]]


In [67]:
arr = arr.transpose()
print(arr)

[[3 2 1]
 [6 5 4]]


### argsort()

In [68]:
arr_1d = np.array([2, 1, 3, 5, 4, 10, 7, 6])

sorted_indices_array = np.argsort(arr_1d)
print(sorted_indices_array)

[1 0 2 4 3 7 6 5]


basically above function give the index of original element in the given array after sorting

### Ranking recommened system

In [69]:
similarity_scores = [0.28, 0.85, 0.11, 0.65, 0.91]
sorted_similiarity_scores = np.argsort(similarity_scores)
top_3_items = sorted_similiarity_scores[-3:][::-1]
print(top_3_items)

[4 1 3]


### Concatination arrays

In [70]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4 5 6]


In [71]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[4, 5, 6], [6, 7, 8]])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [6 7 8]]


In [72]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[4, 5, 6], [6, 7, 8]])

arr3 = np.concatenate((arr1, arr2), axis = 1)
print(arr3)

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]


In [73]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[4, 5, 6], [6, 7, 8]])

arr3 = np.concatenate((arr1, arr2), axis = 0)
print(arr3)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [6 7 8]]


### Reshape

In [74]:
arr_1d

array([ 2,  1,  3,  5,  4, 10,  7,  6])

In [75]:
arr_2d = arr_1d.reshape(4, 2)
arr_2d

array([[ 2,  1],
       [ 3,  5],
       [ 4, 10],
       [ 7,  6]])

In [76]:
arr_2d = arr_1d.reshape(2, 4)
arr_2d

array([[ 2,  1,  3,  5],
       [ 4, 10,  7,  6]])

two methods to concatenate

concat -> [in pandas deals with labeled-data]
concatenate -> [in numpy array-focused]

In [77]:
arr_2d = arr_2d.reshape(-1)
arr_2d

array([ 2,  1,  3,  5,  4, 10,  7,  6])

arr.reshape(-1) is used to flattened any kind of array

### Split Method

In [78]:
arr_1d

array([ 2,  1,  3,  5,  4, 10,  7,  6])

In [79]:
split_arr = np.split(arr_1d, 4)
split_arr

[array([2, 1]), array([3, 5]), array([ 4, 10]), array([7, 6])]

In [80]:
split_arr = np.split(arr_1d, 3)
split_arr

ValueError: array split does not result in an equal division

In [81]:
split_arr = np.split(arr_1d, 5)
split_arr

ValueError: array split does not result in an equal division

In [82]:
split_arr = np.split(arr_1d, 2)
split_arr

[array([2, 1, 3, 5]), array([ 4, 10,  7,  6])]

### Statistical Operations: Mean, Median, Mode

In [83]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

mean_all = np.mean(arr)
print(mean_all)

3.5


In [84]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

mean_axis_0 = np.mean(arr, axis = 0) # here axis = 0 is reffered to column
print(mean_axis_0)

[2.5 3.5 4.5]


In [85]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

mean_axis_1 = np.mean(arr, axis = 1) # here axis = 1 is reffered to row
print(mean_axis_1)

[2. 5.]


np.std => standard deviation

np.median => median

np.min => minimum value

np.max => maximum value

np.var => variance

np.sum => sum



### Data creation ways using NumPy

In [86]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [87]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [88]:
arr = np.zeros((2, 3, 4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [89]:
arr = np.zeros((2, 3, 4), dtype = 'int')
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [90]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [91]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [92]:
arr = np.ones((2, 3, 4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [93]:
arr = np.ones((2, 3, 4), dtype = 'int')
print(arr)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [94]:
arr = np.full((2, 3, 4), np.nan)
print(arr)

[[[nan nan nan nan]
  [nan nan nan nan]
  [nan nan nan nan]]

 [[nan nan nan nan]
  [nan nan nan nan]
  [nan nan nan nan]]]


In [95]:
arr = np.full((2, 3, 4), np.nan, dtype = 'int')
print(arr)

[[[-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]]]


/usr/local/lib/python3.12/dist-packages/numpy/_core/numeric.py:362: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')


In [96]:
arr = np.full((2, 3, 4), np.nan, dtype = 'str')
print(arr)

[[['n' 'n' 'n' 'n']
  ['n' 'n' 'n' 'n']
  ['n' 'n' 'n' 'n']]

 [['n' 'n' 'n' 'n']
  ['n' 'n' 'n' 'n']
  ['n' 'n' 'n' 'n']]]


In [97]:
arr = np.full((2, 3, 4), np.nan, dtype = 'bool')
print(arr)

[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


### Identity Matrix

In [98]:
identity_3_cross_4 = np.eye(3, 4)
print(identity_3_cross_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### np.arange(strat, stop, step_size)**bold text**

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(3, 13, 2)

array([ 3,  5,  7,  9, 11])

### np.random()

In [101]:
np.random.random(5)

array([0.25388816, 0.45161165, 0.51481522, 0.21121953, 0.08947845])

In [103]:
np.random.random_sample(5)

array([0.87097598, 0.51324262, 0.07226643, 0.72392692, 0.66372887])

In [104]:
np.random.random_integers(5)

/tmp/ipython-input-339360557.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5)


np.int64(2)

In [105]:
np.random.random_integers(5, 10)

/tmp/ipython-input-3916089515.py:1: DeprecationWarning: This function is deprecated. Please call randint(5, 10 + 1) instead
  np.random.random_integers(5, 10)


np.int64(7)

In [106]:
np.random.randint(2, 29)

6

In [120]:
np.random.seed(10)
np.random.random((2, 3))

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665]])

np.linspace(start, stop, num, endpoint, retstep, dtype)

In [122]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [136]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])