# NumPy

In [2]:
import numpy as np

## Creation of a numpy array from a list

In [3]:
array_from_a_list = np.array([1, 2, 3, 4, 5])
print(array_from_a_list)

[1 2 3 4 5]


In [4]:
type(array_from_a_list)

numpy.ndarray

In [6]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

[1 2 3 4 5]


## 2D array

In [7]:
array_2d = np.array(
    [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
    ]
)

In [8]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
type(array_2d)

numpy.ndarray

## 3D array

In [17]:
array_3d = np.array([[[1, 2],[True, 4]],[[5.0, 6],[7, 8]],[[9, 10], [11, 12]]])

print(array_3d)

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [18]:
type(array_3d)

numpy.ndarray

In [19]:
array_2d.ndim

2

In [20]:
array_3d.ndim

3

In [21]:
array_from_a_list.shape

(5,)

In [22]:
array_2d.shape

(3, 3)

In [23]:
array_3d.shape

(3, 2, 2)

In [26]:
trial = np.array([1, 3, 'hey', 4], dtype = 'U')

In [27]:
print(trial)

['1' '3' 'hey' '4']


If you create an np.array with mixed data types, like np.array([1, 2, "Hello", 4]), NumPy does not throw an error. Instead, it implicitly typecasts all elements to a single, most accommodating data type.

How typecasting works
When you pass a list of mixed-type Python objects to np.array(), NumPy follows a set of promotion rules to find the most suitable common data type for all elements.
Find the most complex type: NumPy scans the input list to identify the most complex or flexible data type. The hierarchy for standard Python objects is: integers are simpler than floats, which are simpler than strings.
Promote all elements: Once the most accommodating type is found, NumPy converts every other element into that type.
Resulting dtype: The new array's dtype attribute will reflect the common data type.

For np.array([1, 2, "Hello", 4]):
The elements are two integers (1, 2), one string ("Hello"), and another integer (4).
The string "Hello" is the most complex type.
NumPy converts the integers 1, 2, and 4 into string representations '1', '2', and '4'.
The resulting array is array(['1', '2', 'Hello', '4']) with a dtype of <U5 (Unicode string with a maximum length of 5).

Why no error is shown
An error is not shown because NumPy's type promotion is designed to automatically handle mixed types by casting up to the most general type possible. It does this to maintain its core principle of working with homogeneous data and to avoid a crash when a simple conversion is possible.
Explicit vs. implicit conversion: NumPy will only throw an error if you explicitly tell it to convert to an incompatible data type. For example, if you were to force your array to an integer dtype, it would fail because the string "Hello" cannot be converted to an integer.
A "best guess" approach: By automatically casting, NumPy makes a "best guess" at what the user intended to do when faced with mixed data. This behavior is convenient but can hide potential performance issues if not used with care.

In [28]:
array_3d.dtype

dtype('float64')

In [29]:
array_ = np.array([5, -7.4, 'Hey', 7.4, True])

In [30]:
array_.dtype

dtype('<U32')

itemsize returns the size in bytes of each element present in array

In [31]:
print(f"item size of array_ is: {array_.itemsize}")

item size of array_ is: 128


data provides a direct buffer to the memory location where the actual array is present or stored

In [32]:
print(f"Data buffere is actually present at memory location: {array_.data}")

Data buffere is actually present at memory location: <memory at 0x788c7531ee00>


## Indexing and slicing in NumPy

In [33]:
array_from_a_list

array([1, 2, 3, 4, 5])

In [34]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array_3d

array([[[ 1.,  2.],
        [ 1.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]])

In [36]:
print(array_from_a_list[2])

3


In [39]:
print(array_2d[1])

[4 5 6]


In [40]:
print(array_3d[0])

[[1. 2.]
 [1. 4.]]


In [41]:
print(array_2d[2][2])

9


In [42]:
print(array_2d[2, 2])

9


In [43]:
print(array_3d[1, 1, 1])

8.0


In [44]:
print(array_3d[1][1][1])

8.0


In [45]:
print(array_3d[1, 1][1])

8.0


In [46]:
print(array_from_a_list[1: 4])

[2 3 4]


In [47]:
print(array_2d[1:3])

[[4 5 6]
 [7 8 9]]


In [48]:
print(array_2d[1:3, 1:2])

[[5]
 [8]]


In [49]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
print(array_2d[0:3, 0:1])

[[1]
 [4]
 [7]]


In [51]:
print(array_2d[0:3][0:1])

[[1 2 3]]


In [53]:
print(array_2d[0:3, 0:2][0:1])

[[1 2]]


In [55]:
print(array_2d[0:3][0:2][0:1])

[[1 2 3]]


upar wale ka work flow aise hoga

In [61]:
print(array_2d[0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
print(array_2d[0:3][0:2])

[[1 2 3]
 [4 5 6]]


In [63]:
print(array_2d[0:3][0:2][0:1])

[[1 2 3]]


In [66]:
print(array_2d[0:3][0:2][0:1, 0:2])

[[1 2]]


In [67]:
array_3d

array([[[ 1.,  2.],
        [ 1.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]])

In [68]:
print(array_3d[0:])

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [69]:
print(array_3d[0:3][0:2])

[[[1. 2.]
  [1. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [70]:
print(array_3d[0:3][0:2][0:1])

[[[1. 2.]
  [1. 4.]]]


In [71]:
print(array_3d[0:3][0:2][0:1][0:1])

[[[1. 2.]
  [1. 4.]]]


In [72]:
print(array_3d[0:3])

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [73]:
print(array_3d[0:3, 0:2])

[[[ 1.  2.]
  [ 1.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [74]:
print(array_3d[0:3,0:2,0:1])

[[[ 1.]
  [ 1.]]

 [[ 5.]
  [ 7.]]

 [[ 9.]
  [11.]]]
